# Generated by Django 4.0.3 on 2022-03-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_grade_subject_delete_grades_grade_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='grade',
            field=models.IntegerField(null=True),
        ),
    ]
