# Generated by Django 4.0.3 on 2022-03-11 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_group_subject_grade_alter_grade_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='grade',
        ),
        migrations.AddField(
            model_name='student',
            name='pair',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='diary.student'),
        ),
        migrations.AddField(
            model_name='subject',
            name='student',
            field=models.ManyToManyField(through='diary.Grade', to='diary.student'),
        ),
    ]
