# Generated by Django 4.0.3 on 2022-03-11 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_remove_subject_grade_student_pair_subject_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='pair',
        ),
    ]
