# Generated by Django 4.0.3 on 2022-03-11 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0007_remove_student_pair'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='pair',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='diary.student'),
        ),
    ]
