# Generated by Django 4.0.3 on 2022-03-11 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0008_student_pair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='pair',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='diary.student'),
        ),
    ]
