# Generated by Django 4.0.3 on 2022-03-11 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0011_alter_student_group_alter_student_mentor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='mentor',
        ),
        migrations.AlterField(
            model_name='student',
            name='pair',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='diary.student'),
        ),
    ]
