# Generated by Django 4.0.3 on 2022-03-11 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0012_remove_student_mentor_alter_student_pair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='pair',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, parent_link=True, to='diary.student'),
        ),
    ]
