# Generated by Django 4.0.3 on 2022-03-11 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0014_alter_student_group_remove_student_pair_student_pair'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='pair',
        ),
        migrations.AddField(
            model_name='student',
            name='mentor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentee', to='diary.student'),
        ),
    ]
